### ISSUE TITLE
zipper build fails with java.io.FileNotFoundException

### ISSUE THREAD

**Issue by junkfactory** [joestelmach/zipper#3]
Hi, came across zipper through google. I've been trying it out for evaluation but my build is failing with java.io.FileNotFoundException.

Some relevant info:

Directory structure

rpwebapp
-- src
------ main
---------- resources
---------- webapp
-------------- resources
------------------- css
------------------- js

zipper.properties in src/main/resources

webroot=src/main/webapp
output.dir=static
js.asset.jsbase=**/*.js
css.asset.cssbase=**/*.css

running mvn zipper:zipper

[INFO] --- zipper:0.2.3:zipper (default-cli) @ rpwebapp ---
[INFO] zipper.properties found: C:\projects\rpapps\rentpaymentapps\rpwebapp/src\main\resources\zippe                            r.properties
[INFO] lint checking resources\js\jquery-1.7.1.min.js
..... skipped .....
[INFO] optimizing resources\js\jquery-1.7.1.min.js with WHITESPACE_ONLY
[ERROR] 
java.io.FileNotFoundException: C:\projects\rpapps\rentpaymentapps\rpwebapp\target\classes\static\res                            ources\js\jquery-1.7.1.min.js (The system cannot find the path specified)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:179)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:131)
        at com.joestelmach.zipper.plugin.JSOptimizerClosure.optimize(JSOptimizerClosure.java:65)
        at com.joestelmach.zipper.plugin.ZipperMojo.jsOptimize(ZipperMojo.java:156)
        at com.joestelmach.zipper.plugin.ZipperMojo.execute(ZipperMojo.java:70)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.j                            ava:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu                            ilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu                            ilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter                            .java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

Could it be that zipper is not creating the directory hierarchy in output.dir ?

**Comment by junkfactory** [comment]
Guess it is expecting "/" where windows has "\".
